# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Python image from the Docker Hub
FROM python:3.11-slim-bookworm

# Set the working directory in the container
WORKDIR /app

# Copy the project files into the working directory
COPY . /app

# Install the required dependencies
RUN pip install --no-cache-dir hatchling && \
    pip install --no-cache-dir -r requirements.txt

# Expose the port that the server runs on
EXPOSE 8000

# Set the environment path
ENV PYTHONPATH "${PYTHONPATH}:/app/src"

# Run the application
ENTRYPOINT ["hatch", "run", "world_bank_mcp_server"]
