#!/usr/bin/env Rscript
# =============================================================================
# P6 Three-Level Meta-Analysis: Internationalization → Firm Performance
# =============================================================================
# Script:  p6_real_mara.R
# Input:   ../data/p6_study_database.csv  (generated by p6_parse_database.py)
# Output:  ../results/                    (tables + plot data)
#
# Model:   Three-level MARA via metafor::rma.mv()
#          random = ~ 1 | study_id / effect_id   (REML)
# Effect:  Fisher's z-transformed correlation (ZCOR via escalc)
# Target:  APJM / IBR / JIBS journal format
#
# Moderators:
#   H1 — cDAI level (H > M > L) → positive gradient
#   H2 — ICRV regime (I > II > III > FR/MX)
#   H3 — DPL phase (FOL > SPN > PRE)
#
# Usage (local R):
#   Rscript p6_real_mara.R
#
# Usage (Docker rocker/tidyverse):
#   docker run --rm -v $(pwd):/analysis rocker/tidyverse:4.3.2 \
#     Rscript /analysis/p6/scripts/p6_real_mara.R
# =============================================================================

suppressPackageStartupMessages({
  library(metafor)
  library(dplyr)
  library(readr)
})

# ── Paths ────────────────────────────────────────────────────────────────────
script_dir  <- tryCatch(dirname(normalizePath(sys.frame(1)$ofile)),
                        error = function(e) getwd())
data_file   <- file.path(script_dir, "..", "data", "p6_study_database.csv")
results_dir <- file.path(script_dir, "..", "results")
dir.create(results_dir, showWarnings = FALSE, recursive = TRUE)

cat("=============================================================\n")
cat("P6 Three-Level MARA — Internationalization–Performance\n")
cat("=============================================================\n\n")

# ── Load & Prepare Data ──────────────────────────────────────────────────────
cat("Loading:", data_file, "\n")
raw <- read_csv(data_file, show_col_types = FALSE)

# Main analysis sample: include_flag == 1
dat <- raw %>% filter(include_flag == 1)
cat(sprintf("Sample: K = %d effect rows, k = %d unique studies\n\n",
            nrow(dat), n_distinct(dat$study_id)))

# Fisher's z transformation (escalc applies 1/(n-3) sampling variance)
dat <- escalc(measure = "ZCOR", ri = r, ni = n, data = as.data.frame(dat),
              var.names = c("yi", "vi"))

# Factor encoding
dat$icrv_f <- factor(dat$icrv,
                     levels = c("I", "II", "III", "FR", "MX"))
dat$cdai_f <- factor(dat$cdai,
                     levels = c("L", "M", "H"))
dat$cdai_num <- as.integer(dat$cdai_f)          # L=1, M=2, H=3
dat$dpl_f  <- factor(dat$dpl,
                     levels = c("PRE", "SPN", "FOL"))

# ── Helper: Back-transform z → r ─────────────────────────────────────────────
z2r <- function(z) tanh(z)  # == transf.ztor()

print_r <- function(beta, cilb, ciub, pval = NA) {
  r   <- round(z2r(beta),  3)
  lo  <- round(z2r(cilb),  3)
  hi  <- round(z2r(ciub),  3)
  p_s <- if (!is.na(pval)) sprintf(", p = %.4f", pval) else ""
  sprintf("r = %.3f [%.3f, %.3f]%s", r, lo, hi, p_s)
}

# ── Helper: I² for three-level model (Cheung 2014 approximation) ─────────────
i2_threelevel <- function(mod) {
  v_bar <- mean(mod$vi, na.rm = TRUE)
  s2    <- sum(mod$sigma2)
  list(
    I2_total   = round(100 * s2 / (s2 + v_bar), 1),
    I2_between = round(100 * mod$sigma2[1] / (s2 + v_bar), 1),
    I2_within  = round(100 * mod$sigma2[2] / (s2 + v_bar), 1),
    tau2_total = round(s2, 5)
  )
}

# =============================================================================
# MODEL 0 — Baseline Three-Level Random-Effects MARA
# =============================================================================
cat("─────────────────────────────────────────────────────────────\n")
cat("MODEL 0: Baseline Three-Level MARA\n")
cat("─────────────────────────────────────────────────────────────\n")

m0 <- rma.mv(
  yi = yi, V = vi,
  random = ~ 1 | study_id / effect_id,
  data   = dat,
  method = "REML",
  slab   = paste(dat$author, dat$year)
)
print(m0)

i2 <- i2_threelevel(m0)
cat(sprintf("\nPooled effect : %s\n",
            print_r(m0$beta[1], m0$ci.lb[1], m0$ci.ub[1], m0$pval[1])))
cat(sprintf("sigma²(study) : %.5f  |  sigma²(effect): %.5f\n",
            m0$sigma2[1], m0$sigma2[2]))
cat(sprintf("I² total      : %.1f%%  (between-study: %.1f%%, within-study: %.1f%%)\n",
            i2$I2_total, i2$I2_between, i2$I2_within))
cat(sprintf("tau²          : %.5f\n\n", i2$tau2_total))

# Two-level fallback (for trim-and-fill / leave-one-out compatibility)
m0_2L <- rma(yi = yi, vi = vi, data = dat, method = "REML")

# =============================================================================
# MODERATOR ANALYSES
# =============================================================================

# ── MODEL 1: ICRV Regime ──────────────────────────────────────────────────────
cat("─────────────────────────────────────────────────────────────\n")
cat("MODEL 1: ICRV Regime Moderation (H2)\n")
cat("─────────────────────────────────────────────────────────────\n")

# Drop SIDS (k=0) and keep only regimes with k >= 3
icrv_counts <- table(dat$icrv)
cat("Effect rows per ICRV regime:", "\n")
print(icrv_counts)

m1 <- rma.mv(
  yi = yi, V = vi,
  mods   = ~ icrv_f - 1,
  random = ~ 1 | study_id / effect_id,
  data   = dat, method = "REML"
)
print(m1)

# ICRV coefficients back-transformed
icrv_levels <- rownames(m1$beta)
cat("\nICRV regime effects (r scale):\n")
for (i in seq_len(nrow(m1$beta))) {
  k_i <- sum(dat$icrv == sub("icrv_f", "", icrv_levels[i]))
  cat(sprintf("  %s  k=%d  %s\n",
              icrv_levels[i],
              k_i,
              print_r(m1$beta[i], m1$ci.lb[i], m1$ci.ub[i], m1$pval[i])))
}
cat(sprintf("\nOmnibus Q_M(%d) = %.2f, p = %.4f\n\n",
            m1$QMdf[1], m1$QM, m1$QMp))

# ── MODEL 2: cDAI Level ───────────────────────────────────────────────────────
cat("─────────────────────────────────────────────────────────────\n")
cat("MODEL 2: cDAI Digital Adoption Moderation (H1)\n")
cat("─────────────────────────────────────────────────────────────\n")

m2_cat <- rma.mv(
  yi = yi, V = vi,
  mods   = ~ cdai_f - 1,
  random = ~ 1 | study_id / effect_id,
  data   = dat, method = "REML"
)
print(m2_cat)

cdai_levs <- rownames(m2_cat$beta)
cat("\ncDAI level effects (r scale):\n")
for (i in seq_len(nrow(m2_cat$beta))) {
  k_i <- sum(dat$cdai == sub("cdai_f", "", cdai_levs[i]))
  cat(sprintf("  %s  k=%d  %s\n",
              cdai_levs[i],
              k_i,
              print_r(m2_cat$beta[i], m2_cat$ci.lb[i], m2_cat$ci.ub[i], m2_cat$pval[i])))
}
cat(sprintf("\nOmnibus Q_M(%d) = %.2f, p = %.4f\n\n",
            m2_cat$QMdf[1], m2_cat$QM, m2_cat$QMp))

# Also as linear trend
m2_lin <- rma.mv(
  yi = yi, V = vi,
  mods   = ~ cdai_num,
  random = ~ 1 | study_id / effect_id,
  data   = dat, method = "REML"
)
cat(sprintf("cDAI linear trend: b = %.4f, p = %.4f\n\n",
            m2_lin$beta[2], m2_lin$pval[2]))

# ── MODEL 3: DPL Phase ────────────────────────────────────────────────────────
cat("─────────────────────────────────────────────────────────────\n")
cat("MODEL 3: DPL Phase Moderation (H3)\n")
cat("─────────────────────────────────────────────────────────────\n")

m3 <- rma.mv(
  yi = yi, V = vi,
  mods   = ~ dpl_f - 1,
  random = ~ 1 | study_id / effect_id,
  data   = dat, method = "REML"
)
print(m3)

dpl_levs <- rownames(m3$beta)
cat("\nDPL phase effects (r scale):\n")
for (i in seq_len(nrow(m3$beta))) {
  k_i <- sum(dat$dpl == sub("dpl_f", "", dpl_levs[i]))
  cat(sprintf("  %s  k=%d  %s\n",
              dpl_levs[i],
              k_i,
              print_r(m3$beta[i], m3$ci.lb[i], m3$ci.ub[i], m3$pval[i])))
}
cat(sprintf("\nOmnibus Q_M(%d) = %.2f, p = %.4f\n\n",
            m3$QMdf[1], m3$QM, m3$QMp))

# ── MODEL 4: Combined Moderators ──────────────────────────────────────────────
cat("─────────────────────────────────────────────────────────────\n")
cat("MODEL 4: Combined Moderators\n")
cat("─────────────────────────────────────────────────────────────\n")

m4 <- rma.mv(
  yi = yi, V = vi,
  mods   = ~ icrv_f + cdai_num + dpl_f,
  random = ~ 1 | study_id / effect_id,
  data   = dat, method = "REML"
)
print(m4)
cat(sprintf("\nOmnibus Q_M(%d) = %.2f, p = %.4f\n\n",
            m4$QMdf[1], m4$QM, m4$QMp))

# R² analog: proportion of between-study heterogeneity explained
R2 <- max(0, (m0$sigma2[1] - m4$sigma2[1]) / m0$sigma2[1])
cat(sprintf("R² analog (sigma²_study reduction): %.1f%%\n\n", R2 * 100))

# =============================================================================
# PUBLICATION BIAS ASSESSMENT
# =============================================================================
cat("─────────────────────────────────────────────────────────────\n")
cat("PUBLICATION BIAS\n")
cat("─────────────────────────────────────────────────────────────\n")

# Egger's test adapted for multilevel (se as moderator)
dat$se_yi <- sqrt(dat$vi)
m_egger <- rma.mv(
  yi = yi, V = vi,
  mods   = ~ se_yi,
  random = ~ 1 | study_id / effect_id,
  data   = dat, method = "REML"
)
cat(sprintf("Egger's test (SE as moderator):\n  b = %.4f, SE = %.4f, p = %.4f\n",
            m_egger$beta[2], m_egger$se[2], m_egger$pval[2]))
if (m_egger$pval[2] < 0.05) {
  cat("  *** Significant funnel asymmetry detected ***\n")
} else {
  cat("  No significant funnel asymmetry\n")
}

# Rank correlation test (Begg & Mazumdar on two-level model)
rkt <- ranktest(m0_2L)
cat(sprintf("\nRank correlation (Begg): tau = %.3f, p = %.4f\n",
            rkt$tau, rkt$pval))

# Trim-and-fill (on two-level for compatibility)
taf <- trimfill(m0_2L)
r_adj  <- z2r(taf$beta[1])
k_imp  <- taf$k0
cat(sprintf("\nTrim-and-fill:\n  k imputed = %d\n", k_imp))
cat(sprintf("  Adjusted pooled r = %.3f [%.3f, %.3f]\n",
            r_adj,
            z2r(taf$ci.lb[1]),
            z2r(taf$ci.ub[1])))

# Vevea-Hedges selection model (if selmodel available)
tryCatch({
  sel <- selmodel(m0_2L, type = "stepfun", steps = c(0.025, 0.5))
  cat(sprintf("\nVevea-Hedges selection model:\n  Adjusted z = %.4f, r ≈ %.3f\n",
              sel$beta[1], z2r(sel$beta[1])))
}, error = function(e) {
  cat("\nVevea-Hedges: not available or failed:", conditionMessage(e), "\n")
})

# Fail-safe N
fsn_val <- fsn(dat$yi, dat$vi)
cat(sprintf("\nFail-safe N (Rosenthal): %d\n", fsn_val$fsnum))

# =============================================================================
# SENSITIVITY ANALYSES
# =============================================================================
cat("\n─────────────────────────────────────────────────────────────\n")
cat("SENSITIVITY ANALYSES\n")
cat("─────────────────────────────────────────────────────────────\n")

# 1. Leave-one-out (two-level for speed; k=235 studies)
loo <- leave1out(m0_2L)
r_loo <- z2r(loo$estimate)
cat(sprintf("Leave-one-out range: r = [%.3f, %.3f]\n",
            min(r_loo, na.rm = TRUE),
            max(r_loo, na.rm = TRUE)))
cat(sprintf("Studies changing direction: %d / %d\n",
            sum(r_loo < 0, na.rm = TRUE),
            length(r_loo)))

# 2. Exclude estimated r values
dat_confirmed <- dat %>% filter(is_estimated == 0)
m0_conf <- rma.mv(
  yi = yi, V = vi,
  random = ~ 1 | study_id / effect_id,
  data   = dat_confirmed, method = "REML"
)
cat(sprintf("\nConfirmed r only (k=%d / K=%d):\n  %s\n",
            n_distinct(dat_confirmed$study_id), nrow(dat_confirmed),
            print_r(m0_conf$beta[1], m0_conf$ci.lb[1], m0_conf$ci.ub[1],
                    m0_conf$pval[1])))

# 3. Exclude very small samples (n < 30)
dat_n30 <- dat %>% filter(n >= 30)
m0_n30 <- rma.mv(
  yi = yi, V = vi,
  random = ~ 1 | study_id / effect_id,
  data   = dat_n30, method = "REML"
)
cat(sprintf("\nExclude n < 30 (K=%d):\n  %s\n",
            nrow(dat_n30),
            print_r(m0_n30$beta[1], m0_n30$ci.lb[1], m0_n30$ci.ub[1],
                    m0_n30$pval[1])))

# 4. Accounting-based performance only
dat_acc <- dat %>% filter(fp_type == "ACC")
m0_acc <- rma.mv(
  yi = yi, V = vi,
  random = ~ 1 | study_id / effect_id,
  data   = dat_acc, method = "REML"
)
cat(sprintf("\nACC performance only (K=%d):\n  %s\n",
            nrow(dat_acc),
            print_r(m0_acc$beta[1], m0_acc$ci.lb[1], m0_acc$ci.ub[1],
                    m0_acc$pval[1])))

# 5. FSTS measure only
dat_fsts <- dat %>% filter(doi_type == "FSTS")
m0_fsts <- rma.mv(
  yi = yi, V = vi,
  random = ~ 1 | study_id / effect_id,
  data   = dat_fsts, method = "REML"
)
cat(sprintf("\nFSTS measure only (K=%d):\n  %s\n",
            nrow(dat_fsts),
            print_r(m0_fsts$beta[1], m0_fsts$ci.lb[1], m0_fsts$ci.ub[1],
                    m0_fsts$pval[1])))

# 6. DL estimator robustness
m0_dl <- rma(yi = yi, vi = vi, data = dat, method = "DL")
cat(sprintf("\nDL estimator (two-level): r = %.3f [%.3f, %.3f]\n",
            z2r(m0_dl$beta[1]),
            z2r(m0_dl$ci.lb[1]),
            z2r(m0_dl$ci.ub[1])))

# =============================================================================
# EXPORT RESULTS
# =============================================================================
cat("\n─────────────────────────────────────────────────────────────\n")
cat("EXPORTING RESULTS\n")
cat("─────────────────────────────────────────────────────────────\n")

# Table 1: Baseline model summary
tbl1 <- data.frame(
  model         = "Baseline three-level",
  K_effects     = nrow(dat),
  k_studies     = n_distinct(dat$study_id),
  z_pooled      = round(m0$beta[1], 4),
  r_pooled      = round(z2r(m0$beta[1]), 3),
  r_ci_lo       = round(z2r(m0$ci.lb[1]), 3),
  r_ci_hi       = round(z2r(m0$ci.ub[1]), 3),
  pval          = round(m0$pval[1], 4),
  sigma2_study  = round(m0$sigma2[1], 5),
  sigma2_effect = round(m0$sigma2[2], 5),
  I2_total      = i2$I2_total,
  I2_between    = i2$I2_between,
  I2_within     = i2$I2_within,
  Q_total       = round(m0$QE, 2),
  Q_df          = m0$QEdf,
  Q_pval        = round(m0$QEp, 4)
)
write_csv(tbl1, file.path(results_dir, "table1_baseline.csv"))
cat("Saved: table1_baseline.csv\n")

# Table 2: ICRV moderator results
icrv_rows <- lapply(seq_len(nrow(m1$beta)), function(i) {
  lvl <- sub("icrv_f", "", rownames(m1$beta)[i])
  data.frame(
    regime    = lvl,
    k         = sum(dat$icrv == lvl),
    z_est     = round(m1$beta[i], 4),
    r_est     = round(z2r(m1$beta[i]), 3),
    r_ci_lo   = round(z2r(m1$ci.lb[i]), 3),
    r_ci_hi   = round(z2r(m1$ci.ub[i]), 3),
    pval      = round(m1$pval[i], 4),
    QM        = round(m1$QM, 2),
    QM_pval   = round(m1$QMp, 4)
  )
})
tbl2 <- do.call(rbind, icrv_rows)
write_csv(tbl2, file.path(results_dir, "table2_icrv.csv"))
cat("Saved: table2_icrv.csv\n")

# Table 3: cDAI moderator
cdai_rows <- lapply(seq_len(nrow(m2_cat$beta)), function(i) {
  lvl <- sub("cdai_f", "", rownames(m2_cat$beta)[i])
  data.frame(
    cdai      = lvl,
    k         = sum(dat$cdai == lvl),
    r_est     = round(z2r(m2_cat$beta[i]), 3),
    r_ci_lo   = round(z2r(m2_cat$ci.lb[i]), 3),
    r_ci_hi   = round(z2r(m2_cat$ci.ub[i]), 3),
    pval      = round(m2_cat$pval[i], 4)
  )
})
tbl3 <- do.call(rbind, cdai_rows)
tbl3$QM      <- round(m2_cat$QM, 2)
tbl3$QM_pval <- round(m2_cat$QMp, 4)
write_csv(tbl3, file.path(results_dir, "table3_cdai.csv"))
cat("Saved: table3_cdai.csv\n")

# Table 4: DPL phase moderator
dpl_rows <- lapply(seq_len(nrow(m3$beta)), function(i) {
  lvl <- sub("dpl_f", "", rownames(m3$beta)[i])
  data.frame(
    phase     = lvl,
    k         = sum(dat$dpl == lvl),
    r_est     = round(z2r(m3$beta[i]), 3),
    r_ci_lo   = round(z2r(m3$ci.lb[i]), 3),
    r_ci_hi   = round(z2r(m3$ci.ub[i]), 3),
    pval      = round(m3$pval[i], 4)
  )
})
tbl4 <- do.call(rbind, dpl_rows)
tbl4$QM      <- round(m3$QM, 2)
tbl4$QM_pval <- round(m3$QMp, 4)
write_csv(tbl4, file.path(results_dir, "table4_dpl.csv"))
cat("Saved: table4_dpl.csv\n")

# Table 5: Sensitivity summary
tbl5 <- data.frame(
  analysis    = c("Main analysis", "Confirmed r only",
                  "Exclude n < 30", "ACC performance",
                  "FSTS measure", "DL estimator"),
  K           = c(nrow(dat), nrow(dat_confirmed),
                  nrow(dat_n30), nrow(dat_acc),
                  nrow(dat_fsts), nrow(dat)),
  r_est       = round(c(z2r(m0$beta[1]),
                        z2r(m0_conf$beta[1]),
                        z2r(m0_n30$beta[1]),
                        z2r(m0_acc$beta[1]),
                        z2r(m0_fsts$beta[1]),
                        z2r(m0_dl$beta[1])), 3),
  r_ci_lo     = round(c(z2r(m0$ci.lb[1]),
                        z2r(m0_conf$ci.lb[1]),
                        z2r(m0_n30$ci.lb[1]),
                        z2r(m0_acc$ci.lb[1]),
                        z2r(m0_fsts$ci.lb[1]),
                        z2r(m0_dl$ci.lb[1])), 3),
  r_ci_hi     = round(c(z2r(m0$ci.ub[1]),
                        z2r(m0_conf$ci.ub[1]),
                        z2r(m0_n30$ci.ub[1]),
                        z2r(m0_acc$ci.ub[1]),
                        z2r(m0_fsts$ci.ub[1]),
                        z2r(m0_dl$ci.ub[1])), 3)
)
write_csv(tbl5, file.path(results_dir, "table5_sensitivity.csv"))
cat("Saved: table5_sensitivity.csv\n")

# Forest plot data (for Python figure generation)
forest_dat <- dat %>%
  arrange(icrv, year) %>%
  mutate(
    r_i     = round(z2r(yi), 3),
    r_lo    = round(z2r(yi - 1.96 * sqrt(vi)), 3),
    r_hi    = round(z2r(yi + 1.96 * sqrt(vi)), 3),
    label   = paste(author, year)
  ) %>%
  select(study_id, effect_id, label, r_i, r_lo, r_hi,
         icrv, cdai, dpl, n, doi_type, fp_type)
write_csv(forest_dat, file.path(results_dir, "forest_data.csv"))
cat("Saved: forest_data.csv\n")

# =============================================================================
# FINAL SUMMARY
# =============================================================================
cat("\n=============================================================\n")
cat("ANALYSIS COMPLETE\n")
cat("=============================================================\n")
cat(sprintf("Studies (k)     : %d\n", n_distinct(dat$study_id)))
cat(sprintf("Effects (K)     : %d\n", nrow(dat)))
cat(sprintf("Pooled r        : %.3f [%.3f, %.3f], p = %.4f\n",
            z2r(m0$beta[1]),
            z2r(m0$ci.lb[1]),
            z2r(m0$ci.ub[1]),
            m0$pval[1]))
cat(sprintf("I² total        : %.1f%%\n", i2$I2_total))
cat(sprintf("Publication bias: k_imputed = %d, adj. r = %.3f\n",
            taf$k0, z2r(taf$beta[1])))
cat(sprintf("Results saved to: %s/\n", results_dir))
