"""Authentication layer using streamlit-authenticator.

Sessions are persisted via a signed JWT stored in a browser cookie (HttpOnly).
No credentials or tokens ever appear in the URL.

Credentials live in .streamlit/auth.yaml (gitignored, never committed).
Passwords are stored as bcrypt hashes — never in plain text.

YAML format
-----------
credentials:
  usernames:
    alice:
      name: Alice Martin
      email: alice.martin@epfl.ch
      password: $2b$12$...          # bcrypt hash — generated by CLI
      role: admin                   # admin | reporting
cookie:
  name: is_session
  key: <random-64-char-hex>         # JWT signing key — run: python -m ui.auth genkey
  expiry_days: 0.33                 # 8 hours

Roles
-----
admin     — full access: all pages including run launcher, scheduling, configuration
reporting — read-only: dashboard, publications, statistics

CLI
---
  python -m ui.auth add    <username> <role>   # create user (prompts for password)
  python -m ui.auth remove <username>
  python -m ui.auth passwd <username>          # change password
  python -m ui.auth list
  python -m ui.auth genkey                     # generate a new cookie signing key
"""

from __future__ import annotations

import getpass
import secrets
import sys
from pathlib import Path
from typing import Optional

import yaml
from yaml.loader import SafeLoader
from yaml.dumper import SafeDumper

ROOT      = Path(__file__).resolve().parent.parent
AUTH_FILE = ROOT / ".streamlit" / "auth.yaml"

ROLE_PAGES: dict[str, list[str]] = {
    "admin": [
        "Tableau de bord",
        "Lancer un run",
        "Programmation",
        "Publications",
        "Statistiques",
        "Configuration",
    ],
    "reporting": [
        "Tableau de bord",
        "Publications",
        "Statistiques",
    ],
}

# ── Config I/O ────────────────────────────────────────────────────────────────

def _load_config() -> dict:
    if not AUTH_FILE.exists():
        return {
            "credentials": {"usernames": {}},
            "cookie": {"name": "is_session", "key": "", "expiry_days": 0.33},
        }
    with open(AUTH_FILE, encoding="utf-8") as f:
        return yaml.load(f, Loader=SafeLoader) or {}


def _save_config(config: dict) -> None:
    AUTH_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(AUTH_FILE, "w", encoding="utf-8") as f:
        yaml.dump(config, f, Dumper=SafeDumper, allow_unicode=True,
                  default_flow_style=False)


def _make_authenticator(config: dict):
    import streamlit_authenticator as stauth
    cookie = config.get("cookie", {})
    return stauth.Authenticate(
        config.get("credentials", {"usernames": {}}),
        cookie.get("name", "is_session"),
        cookie.get("key", ""),
        cookie.get("expiry_days", 0.33),
    )


# ── Streamlit runtime API ─────────────────────────────────────────────────────

def login_wall() -> "tuple[str, str]":
    """Block rendering until the user is authenticated.

    Uses streamlit-authenticator for cookie-based persistent sessions.
    The session JWT is stored in a browser cookie — never in the URL.
    Returns (username, role) once authenticated; calls st.stop() otherwise.
    """
    import streamlit as st
    if not AUTH_FILE.exists():
        st.error(
            f"Fichier de credentials manquant : `{AUTH_FILE.relative_to(ROOT)}`  \n"
            "Créez-le avec `python -m ui.auth add <username> <role>`."
        )
        st.stop()

    cookie = _load_config().get("cookie", {})
    key = cookie.get("key", "")
    if not key:
        st.error(
            "La clé de signature du cookie est absente dans `auth.yaml`.  \n"
            "Générez-en une avec `python -m ui.auth genkey`."
        )
        st.stop()
    if len(key.encode()) < 32:
        st.error(
            f"La clé de signature du cookie est trop courte "
            f"({len(key.encode())} octets, minimum 32).  \n"
            "Régénérez-la avec `python -m ui.auth genkey`."
        )
        st.stop()

    config = _load_config()
    authenticator = _make_authenticator(config)

    authenticator.login(
        location="main",
        fields={
            "Form name": "📚 Infoscience Imports",
            "Username":  "Identifiant",
            "Password":  "Mot de passe",
            "Login":     "Se connecter",
        },
    )

    status = st.session_state.get("authentication_status")

    if status is True:
        username  = st.session_state.get("username", "")
        user_data = config["credentials"]["usernames"].get(username, {})
        role      = user_data.get("role", "reporting")
        st.session_state["_auth_role"] = role
        st.session_state["_auth_name"] = user_data.get("name", username)
        # Store authenticator for logout without re-reading config
        st.session_state["_authenticator"] = authenticator
        return username, role

    if status is False:
        st.error("Identifiant ou mot de passe incorrect.")

    st.stop()


def logout() -> None:
    """Invalidate the session cookie and return to the login screen."""
    import streamlit as st
    auth = st.session_state.get("_authenticator")
    if auth is None:
        # Fallback: recreate from config (covers edge cases)
        auth = _make_authenticator(_load_config())
    auth.logout(location="unrendered")
    for k in ("_auth_role", "_auth_name", "_authenticator"):
        st.session_state.pop(k, None)
    st.rerun()


def get_allowed_pages(role: str) -> list[str]:
    return ROLE_PAGES.get(role, ROLE_PAGES["reporting"])


def current_user() -> "tuple[str, str, str]":
    """Return (username, display_name, role) for the active session."""
    import streamlit as st
    return (
        st.session_state.get("username", ""),
        st.session_state.get("_auth_name") or st.session_state.get("name", ""),
        st.session_state.get("_auth_role", "reporting"),
    )


# ── CLI user management ───────────────────────────────────────────────────────

def _hash(password: str) -> str:
    import bcrypt
    return bcrypt.hashpw(password.encode(), bcrypt.gensalt(rounds=12)).decode()


def _cli_add(username: str, role: str) -> None:
    if role not in ROLE_PAGES:
        print(f"Rôle invalide '{role}'. Choix : {', '.join(ROLE_PAGES)}")
        sys.exit(1)
    password = getpass.getpass(f"Mot de passe pour {username!r} : ")
    confirm  = getpass.getpass("Confirmer : ")
    if password != confirm:
        print("Les mots de passe ne correspondent pas.")
        sys.exit(1)
    config = _load_config()
    config.setdefault("credentials", {}).setdefault("usernames", {})[username] = {
        "name":     username,
        "email":    "",
        "password": _hash(password),
        "role":     role,
    }
    _save_config(config)
    print(f"Utilisateur '{username}' ({role}) créé dans {AUTH_FILE}.")


def _cli_remove(username: str) -> None:
    config = _load_config()
    if username not in config.get("credentials", {}).get("usernames", {}):
        print(f"Utilisateur '{username}' introuvable.")
        sys.exit(1)
    del config["credentials"]["usernames"][username]
    _save_config(config)
    print(f"Utilisateur '{username}' supprimé.")


def _cli_passwd(username: str) -> None:
    config = _load_config()
    if username not in config.get("credentials", {}).get("usernames", {}):
        print(f"Utilisateur '{username}' introuvable.")
        sys.exit(1)
    password = getpass.getpass(f"Nouveau mot de passe pour {username!r} : ")
    confirm  = getpass.getpass("Confirmer : ")
    if password != confirm:
        print("Les mots de passe ne correspondent pas.")
        sys.exit(1)
    config["credentials"]["usernames"][username]["password"] = _hash(password)
    _save_config(config)
    print(f"Mot de passe de '{username}' mis à jour.")


def _cli_list() -> None:
    config = _load_config()
    users  = config.get("credentials", {}).get("usernames", {})
    if not users:
        print("Aucun utilisateur configuré.")
        return
    print(f"{'Identifiant':<20} {'Nom':<25} {'Rôle'}")
    print("-" * 55)
    for uname, info in users.items():
        print(f"{uname:<20} {info.get('name', ''):<25} {info.get('role', '')}")


def _cli_genkey() -> None:
    """Generate a new cookie signing key and write it to auth.yaml."""
    config = _load_config()
    key    = secrets.token_hex(32)
    config.setdefault("cookie", {})
    config["cookie"].setdefault("name", "is_session")
    config["cookie"]["key"]          = key
    config["cookie"].setdefault("expiry_days", 0.33)
    _save_config(config)
    print(f"Clé générée et écrite dans {AUTH_FILE}.")
    print(f"  cookie.key = {key}")


if __name__ == "__main__":
    import argparse as _ap
    p = _ap.ArgumentParser(
        description="Gestion des utilisateurs Infoscience Imports UI",
        epilog="Exemple : python -m ui.auth add admin admin",
    )
    sub = p.add_subparsers(dest="cmd", required=True)

    s_add = sub.add_parser("add",    help="Créer un utilisateur")
    s_add.add_argument("username");  s_add.add_argument("role", choices=list(ROLE_PAGES))

    s_rm  = sub.add_parser("remove", help="Supprimer un utilisateur")
    s_rm.add_argument("username")

    sub.add_parser("list",   help="Lister les utilisateurs")
    sub.add_parser("genkey", help="Générer une clé de signature du cookie")

    s_pw  = sub.add_parser("passwd", help="Changer le mot de passe")
    s_pw.add_argument("username")

    args = p.parse_args()
    if   args.cmd == "add":    _cli_add(args.username, args.role)
    elif args.cmd == "remove": _cli_remove(args.username)
    elif args.cmd == "list":   _cli_list()
    elif args.cmd == "passwd": _cli_passwd(args.username)
    elif args.cmd == "genkey": _cli_genkey()
