"text::journal::journal article::data paper": "article-coar-types:c_beb9"
"text::journal::editorial": "article-coar-types:c_b239"
"text::journal": "article-coar-types:c_0640"
"text::journal::journal article": "article-coar-types:c_6501"
"text::journal::journal article::research article": "article-coar-types:c_2df8fbb1"
"text::journal::journal article::review article": "article-coar-types:c_dcae04bc"
"text::journal::journal article::software paper": "article-coar-types:c_7bab"
"text::book/monograph::book part or chapter": "book-coar-types:c_3248"
"text::book/monograph": "book-coar-types:c_2f33"
"text::conference output": "conference-coar-types:c_c94f"
"text::conference output::conference proceedings::conference paper": "conference-coar-types:c_5794"
"text::conference output::conference paper not in proceedings": "conference-coar-types:c_18cp"
"text::conference output::conference proceedings::conference poster": "conference-coar-types:c_6670"
"text::conference output::conference poster not in proceedings": "conference-coar-types:c_18co"
"text::conference output::conference presentation": "conference-coar-types:R60J-J5BD"
"text::conference output::conference proceedings": "conference-coar-types:c_f744"
"dataset::aggregated data": "dataset-coar-types:ACF7-8YT9"
"dataset::clinical trial data": "dataset-coar-types:c_cb28"
"dataset::compiled data": "dataset-coar-types:FXF3-D3G7"
"dataset": "dataset-coar-types:c_ddb1"
"dataset::encoded data": "dataset-coar-types:AM6W-6QAW"
"dataset::experimental data": "dataset-coar-types:63NG-B465"
"dataset::genomic data": "dataset-coar-types:A8F1-NPV9"
"dataset::geospatial data": "dataset-coar-types:2H0M-X761"
"dataset::laboratory notebook": "dataset-coar-types:H41Y-FW7B"
"dataset::measurement and test data": "dataset-coar-types:DD58-GFSX"
"dataset::observational data": "dataset-coar-types:FF4C-28RK"
"dataset::recorded data": "dataset-coar-types:CQMR-7K63"
"software::research software": "dataset-coar-types:c_c950"
"dataset::simulation data": "dataset-coar-types:W2XT-7017"
"software": "dataset-coar-types:c_5ce6"
"software::source code": "dataset-coar-types:QH80-2R4E"
"dataset::survey data": "dataset-coar-types:NHD0-W6SY"
"design": "design-coar-types:542X-3S04"
"image": "design-coar-types:c_c513"
"design::industrial design": "design-coar-types:JBNF-DYAD"
"interactive resource": "design-coar-types:c_e9a0"
"design::layout design": "design-coar-types:BW7T-YM2G"
"image::moving image": "design-coar-types:c_8a7e"
"image::still image": "design-coar-types:c_ecc8"
"image::moving image::video": "design-coar-types:c_12ce"
"interactive resource::website": "design-coar-types:c_7ad9"
"text::blog post": "media-coar-types:c_6947"
"text::magazine": "media-coar-types:c_2cd9"
"text::newspaper article": "media-coar-types:c_998f"
"patent::PCT application": "patent-coar-types:SB3Y-W4EH"
"patent::design patent": "patent-coar-types:C53B-JCY5"
"patent": "patent-coar-types:c_15cd"
"patent::plant patent": "patent-coar-types:Z907-YMBB"
"patent::plant variety protection": "patent-coar-types:GPQ7-G5VE"
"patent::software patent": "patent-coar-types:MW8G-3CR8"
"patent::utility model": "patent-coar-types:9DKX-KSAF"
"text::preprint": "preprint-coar-types:c_816b"
"text::working paper": "preprint-coar-types:c_8042"
"text::report::clinical study": "report-coar-types:c_7877"
"text::report::data management plan": "report-coar-types:c_ab20"
"text::report::policy report": "report-coar-types:c_186u"
"text::report": "report-coar-types:c_93fc"
"text::report::research protocol": "report-coar-types:YZ1N-ZFT9"
"text::report::research report": "report-coar-types:c_18ws"
"text::technical documentation or standard": "report-coar-types:c_71bd"
"text::report::technical report": "report-coar-types:c_18gh"
"teaching material": "teaching-coar-types:c_e059"
"thesis": "thesis-coar-types:c_46ec"
"thesis::doctoral thesis": "thesis-coar-types:c_db06"
"student work::bachelor thesis": "student-coar-types:c_7a1f"
"student work::master thesis": "student-coar-types:c_bdcc"
"student work::semester or other student projects": "student-coar-types:c_18op"
"student work": "student-coar-types:c_46ec"
"other": "publication-coar-types:c_1843"
